/**
 * Canonical AI Work Order domain logic.
 *
 * Work Orders are repeatable bounded transactions, NOT permanent entitlements.
 * One organization may have many Work Orders. Each has its own scope acceptance.
 *
 * Lifecycle:
 *   draft → awaiting_scope → awaiting_approval → ready_for_checkout
 *         → payment_pending → paid → scoped → in_progress
 *         → needs_client_input → in_review → delivered → completed
 *         (or cancelled / refunded at any point)
 *
 * Scope status (separate from work status):
 *   draft → needs_review → standard → accepted
 *   (or custom_scope_required for expanded scope)
 */

import { createServiceClient } from '@/lib/supabase'
import { createHash } from 'crypto'

// Re-export types from the types-only file (safe for client components)
export type {
  WorkOrderStatus,
  WorkOrderScopeStatus,
  ScopeVersionStatus,
  WorkType,
  FulfillmentState,
  WorkOrder,
  WorkOrderScopeAcceptance,
  WorkOrderScopeVersion,
  WorkOrderUpdate,
  WorkOrderDeliverable,
  ScopeSnapshot,
  ArtifactType,
  SourceRequestType,
  UpdateAuthorRole,
  UpdateType,
} from '@/lib/commercial/work-order-types'
export {
  statusLabel,
  statusActionLabel,
  statusAdvisorLabel,
  statusPriority,
  artifactTypeLabel,
  workTypeLabel,
} from '@/lib/commercial/work-order-types'

// Import types for internal use
import type {
  WorkOrderStatus,
  WorkOrderScopeStatus,
  ScopeVersionStatus,
  WorkType,
  FulfillmentState,
  WorkOrder,
  WorkOrderScopeAcceptance,
  WorkOrderScopeVersion,
  WorkOrderUpdate,
  WorkOrderDeliverable,
  ScopeSnapshot,
  ArtifactType,
  SourceRequestType,
  UpdateAuthorRole,
  UpdateType,
} from '@/lib/commercial/work-order-types'

// ============================================
// Scope rendering
// ============================================

/**
 * Build a canonical scope snapshot for a standard $500 Work Order.
 * The server generates this — the client does not supply the hash.
 */
export function buildStandardScopeSnapshot(params: {
  title: string
  workType: WorkType
  desiredOutcome: string
  scopeIncluded?: string
  scopeExcluded?: string
  requiredInputs?: string
  deliverableDescription?: string
  targetDate?: string | null
}): ScopeSnapshot {
  return {
    work_type: params.workType,
    title: params.title,
    desired_outcome: params.desiredOutcome,
    scope_included: params.scopeIncluded || 'One bounded piece of work as described in the intake and agreed in this scope.',
    scope_excluded: params.scopeExcluded || 'Work beyond the defined scope, additional integrations, or multi-system architecture. These may require additional Work Orders or a custom engagement.',
    required_inputs: params.requiredInputs || 'Access to relevant systems, data, or documentation as needed to complete the defined outcome.',
    deliverable_description: params.deliverableDescription || 'A focused deliverable matching the agreed scope: analysis, design, recommendation, configuration, or bounded implementation.',
    target_timing: params.targetDate || null,
    price_cents: 50000,
    currency: 'USD',
    assumptions: [
      'Standard Work Order covers one bounded outcome.',
      'If the work is larger than one standard Work Order, additional Work Orders or a custom scope will be discussed before proceeding.',
      'The answer is allowed to be no — a recommendation to wait, buy, or simplify is a valid outcome.',
    ],
  }
}

/**
 * Hash the scope snapshot for immutable acceptance record.
 */
export function hashScopeSnapshot(snapshot: ScopeSnapshot): string {
  const canonical = JSON.stringify({
    work_type: snapshot.work_type,
    title: snapshot.title,
    desired_outcome: snapshot.desired_outcome,
    scope_included: snapshot.scope_included,
    scope_excluded: snapshot.scope_excluded,
    required_inputs: snapshot.required_inputs,
    deliverable_description: snapshot.deliverable_description,
    target_timing: snapshot.target_timing,
    price_cents: snapshot.price_cents,
    currency: snapshot.currency,
    assumptions: snapshot.assumptions,
  })
  return createHash('sha256').update(canonical).digest('hex')
}

// ============================================
// Status language mapping (customer-facing)
// ============================================

// ============================================
// Database operations (service role)
// ============================================

/**
 * Create a Work Order draft. work_order_number is auto-generated by trigger.
 */
export async function createWorkOrderDraft(opts: {
  organizationId: string
  requestedByUserId?: string
  title: string
  workType?: WorkType
  desiredOutcome?: string
  scopeIncluded?: string
  scopeExcluded?: string
  requiredInputs?: string
  deliverableDescription?: string
  legacyQualificationId?: string
  standardPriceCents?: number
  targetDate?: string | null
  metadata?: Record<string, unknown>
}): Promise<{ workOrderId: string; workOrderNumber: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_orders')
    .insert({
      organization_id: opts.organizationId,
      requested_by_user_id: opts.requestedByUserId || null,
      source_offer_key: 'ai_automation_blueprint',
      legacy_qualification_id: opts.legacyQualificationId || null,
      title: opts.title,
      work_type: opts.workType || 'other',
      desired_outcome: opts.desiredOutcome || null,
      scope_included: opts.scopeIncluded || null,
      scope_excluded: opts.scopeExcluded || null,
      required_inputs: opts.requiredInputs || null,
      deliverable_description: opts.deliverableDescription || null,
      scope_status: 'draft',
      status: 'draft',
      standard_price_cents: opts.standardPriceCents ?? 50000,
      currency: 'USD',
      target_date: opts.targetDate || null,
      metadata: opts.metadata || {},
    })
    .select('id, work_order_number')
    .single()

  if (error || !data) {
    return { error: error?.message || 'Failed to create Work Order' }
  }

  return { workOrderId: data.id, workOrderNumber: data.work_order_number }
}

/**
 * Create a Work Order draft for custom/expanded scope.
 * Placed in advisor review queue, NOT checkout.
 */
export async function createCustomScopeWorkOrder(opts: {
  organizationId: string
  requestedByUserId?: string
  title: string
  workType?: WorkType
  desiredOutcome?: string
  legacyQualificationId?: string
  metadata?: Record<string, unknown>
}): Promise<{ workOrderId: string; workOrderNumber: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_orders')
    .insert({
      organization_id: opts.organizationId,
      requested_by_user_id: opts.requestedByUserId || null,
      source_offer_key: 'ai_automation_blueprint',
      legacy_qualification_id: opts.legacyQualificationId || null,
      title: opts.title,
      work_type: opts.workType || 'other',
      desired_outcome: opts.desiredOutcome || null,
      scope_status: 'custom_scope_required',
      status: 'awaiting_scope',
      standard_price_cents: 50000,
      currency: 'USD',
      metadata: { ...opts.metadata || {}, custom_scope: true },
    })
    .select('id, work_order_number')
    .single()

  if (error || !data) {
    return { error: error?.message || 'Failed to create Work Order' }
  }

  return { workOrderId: data.id, workOrderNumber: data.work_order_number }
}

/**
 * Create an immutable scope version for a Work Order.
 *
 * The server generates the snapshot and hash; the caller does NOT supply a
 * hash. The version is inserted as `proposed` (or `sent_to_client` if
 * `sendToClient` is true). The Work Order's `current_scope_version_id` is
 * pointed at the new version and prior non-terminal versions are marked
 * `superseded`.
 *
 * Section B/C: sending/preparing a scope must NEVER write scope_status =
 * 'accepted' / scope_accepted_at / scope_accepted_by. Only
 * `acceptWorkOrderScope` (which calls the `accept_work_order_scope` RPC)
 * records acceptance.
 */
export async function createWorkOrderScopeVersion(opts: {
  workOrderId: string
  scopeSnapshot: ScopeSnapshot
  composedBy: string
  sendToClient?: boolean
}): Promise<{ scopeVersionId: string; versionNumber: number } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const snapshot = opts.scopeSnapshot
  const hash = hashScopeSnapshot(snapshot)

  // Determine next version number for this work order
  const { data: maxVersion } = await sc
    .from('ai_work_order_scope_versions')
    .select('version_number')
    .eq('work_order_id', opts.workOrderId)
    .order('version_number', { ascending: false })
    .limit(1)
    .single()

  const nextVersion = (maxVersion?.version_number ?? 0) + 1

  const versionStatus: ScopeVersionStatus = opts.sendToClient ? 'sent_to_client' : 'proposed'

  const { data: version, error: insertError } = await sc
    .from('ai_work_order_scope_versions')
    .insert({
      work_order_id: opts.workOrderId,
      version_number: nextVersion,
      scope_snapshot: snapshot as unknown as Record<string, unknown>,
      document_hash: hash,
      price_cents: snapshot.price_cents,
      currency: snapshot.currency,
      composed_by: opts.composedBy,
      version_status: versionStatus,
    })
    .select('id, version_number')
    .single()

  if (insertError || !version) {
    return { error: insertError?.message || 'Failed to create scope version' }
  }

  // Supersede prior non-terminal versions (keep historical rows immutable;
  // only their version_status flips to superseded).
  await sc
    .from('ai_work_order_scope_versions')
    .update({ version_status: 'superseded', superseded_by: version.id })
    .eq('work_order_id', opts.workOrderId)
    .neq('id', version.id)
    .in('version_status', ['proposed', 'sent_to_client'])

  // Point the Work Order at the new current version and update mutable
  // scope_* columns (these are convenience copies for display; the
  // immutable source of truth is the scope_versions row).
  const updateFields: Record<string, unknown> = {
    current_scope_version_id: version.id,
    scope_included: snapshot.scope_included,
    scope_excluded: snapshot.scope_excluded,
    required_inputs: snapshot.required_inputs,
    deliverable_description: snapshot.deliverable_description,
    desired_outcome: snapshot.desired_outcome,
    scope_title: snapshot.title,
    scope_price_cents: snapshot.price_cents,
    scope_target_timing: snapshot.target_timing,
    scope_status: opts.sendToClient ? 'sent_to_client' : 'needs_review',
    scope_composed_by: opts.composedBy,
    scope_composed_at: new Date().toISOString(),
  }

  if (opts.sendToClient) {
    // Transition to awaiting_client_acceptance ONLY if currently in a
    // pre-acceptance state. Do NOT touch accepted/paid/etc.
    const { data: wo } = await sc
      .from('ai_work_orders')
      .select('status')
      .eq('id', opts.workOrderId)
      .single()

    if (wo && (wo.status === 'awaiting_scope' || wo.status === 'draft' || wo.status === 'awaiting_client_acceptance')) {
      updateFields.status = 'awaiting_client_acceptance'
    }
  }

  await sc
    .from('ai_work_orders')
    .update(updateFields)
    .eq('id', opts.workOrderId)

  return { scopeVersionId: version.id, versionNumber: version.version_number }
}

/**
 * Get the current offered scope version for a Work Order.
 */
export async function getCurrentScopeVersion(
  workOrderId: string
): Promise<WorkOrderScopeVersion | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('current_scope_version_id')
    .eq('id', workOrderId)
    .single()

  if (!wo?.current_scope_version_id) return null

  const { data: version } = await sc
    .from('ai_work_order_scope_versions')
    .select('*')
    .eq('id', wo.current_scope_version_id)
    .single()

  return (version || null) as WorkOrderScopeVersion | null
}

/**
 * List all scope versions for a Work Order (immutable history).
 */
export async function listScopeVersions(
  workOrderId: string
): Promise<WorkOrderScopeVersion[]> {
  const sc = createServiceClient()
  if (!sc) return []

  const { data } = await sc
    .from('ai_work_order_scope_versions')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('version_number', { ascending: true })

  return (data || []) as WorkOrderScopeVersion[]
}

/**
 * Accept the current scope version for a Work Order.
 *
 * Section C: the client sends only { workOrderId, scopeVersionId, accept }.
 * The server loads the canonical immutable version, validates it is the
 * current offered version, and records acceptance via the
 * `accept_work_order_scope` RPC (transactional — acceptance insert + WO
 * transition + audit row in one transaction).
 *
 * If the acceptor is owner/admin, transition to ready_for_checkout. If the
 * acceptor is a service-seat member (not owner/admin), transition to
 * awaiting_owner_approval so the owner can approve and pay.
 */
export async function acceptWorkOrderScope(opts: {
  workOrderId: string
  scopeVersionId: string
  acceptedBy: string
  isOwnerAdmin: boolean
}): Promise<{ acceptanceId: string; targetStatus: WorkOrderStatus } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const targetStatus: WorkOrderStatus = opts.isOwnerAdmin ? 'ready_for_checkout' : 'awaiting_owner_approval'

  const { data, error } = await sc.rpc('accept_work_order_scope', {
    p_work_order_id: opts.workOrderId,
    p_scope_version_id: opts.scopeVersionId,
    p_accepted_by: opts.acceptedBy,
    p_transition_target: targetStatus,
  })

  if (error || !data) {
    return { error: error?.message || 'Failed to accept scope' }
  }

  return { acceptanceId: data as string, targetStatus }
}

/**
 * Record scope acceptance for a Work Order.
 *
 * DEPRECATED: this function predates immutable scope versions and is kept
 * only for the legacy blueprint/checkout path that creates a standard scope
 * and accepts it in one shot. New code must use `createWorkOrderScopeVersion`
 * + `acceptWorkOrderScope` so the customer sees and accepts the exact
 * version.
 *
 * For the legacy path, this now creates an immutable scope version AND
 * accepts it in the same call (so the acceptance is still recorded against a
 * real version row, not a free-form JSON blob).
 */
export async function recordScopeAcceptance(opts: {
  workOrderId: string
  scopeSnapshot: ScopeSnapshot
  acceptedBy: string
  isOwnerAdmin?: boolean
}): Promise<{ acceptanceId: string } | { error: string }> {
  // Create the immutable version (sent_to_client), then accept it.
  const versionResult = await createWorkOrderScopeVersion({
    workOrderId: opts.workOrderId,
    scopeSnapshot: opts.scopeSnapshot,
    composedBy: opts.acceptedBy,
    sendToClient: true,
  })

  if ('error' in versionResult) {
    return { error: versionResult.error }
  }

  const acceptResult = await acceptWorkOrderScope({
    workOrderId: opts.workOrderId,
    scopeVersionId: versionResult.scopeVersionId,
    acceptedBy: opts.acceptedBy,
    isOwnerAdmin: opts.isOwnerAdmin ?? true,
  })

  if ('error' in acceptResult) {
    return { error: acceptResult.error }
  }

  return { acceptanceId: acceptResult.acceptanceId }
}

/**
 * Link a Stripe checkout session to a Work Order and transition to
 * payment_pending. Uses the validated RPC for the status transition so the
 * audit row is written atomically and the transition matrix is enforced.
 */
export async function linkCheckoutSession(
  workOrderId: string,
  stripeCheckoutSessionId: string
): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  // First set the checkout session id (non-status field), then transition
  // via the RPC. The RPC does not touch stripe_checkout_session_id.
  const { error: linkError } = await sc
    .from('ai_work_orders')
    .update({ stripe_checkout_session_id: stripeCheckoutSessionId })
    .eq('id', workOrderId)

  if (linkError) return { success: false, error: linkError.message }

  const { error: rpcError } = await sc.rpc('transition_work_order_status', {
    p_work_order_id: workOrderId,
    p_new_status: 'payment_pending',
    p_actor_role: 'platform_admin',
    p_note: 'Stripe checkout session created.',
  })

  if (rpcError) {
    // If the transition fails (e.g. already payment_pending from a prior
    // session), that is acceptable — the session id is linked. Surface
    // only genuine errors.
    if (!/invalid_transition/.test(rpcError.message)) {
      return { success: false, error: rpcError.message }
    }
  }
  return { success: true }
}

/**
 * Fulfill a Work Order after Stripe payment succeeds.
 *
 * Section F/G: delegates to the `fulfill_work_order` RPC which atomically:
 *   - validates the Work Order exists
 *   - validates workOrder.organization_id === organization_id (no mis-linking)
 *   - validates the Work Order is in a fulfillable state
 *   - links payment + engagement + stripe_payment_intent_id
 *   - sets purchased_by_user_id when known (NOT null when known)
 *   - sets paid_at (revenue source of truth, NOT scope_accepted_at)
 *   - transitions status to `paid`
 *   - inserts the audit update row
 *
 * Idempotent: if the Work Order is already paid/fulfilled, validates that
 * the existing payment_id and engagement_id match and returns success. A
 * mismatch raises (payment_id_conflict / engagement_id_conflict).
 */
export async function fulfillWorkOrder(opts: {
  workOrderId: string
  organizationId: string
  paymentId: string
  stripePaymentIntentId?: string
  engagementId: string
  purchaserUserId?: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc.rpc('fulfill_work_order', {
    p_work_order_id: opts.workOrderId,
    p_organization_id: opts.organizationId,
    p_payment_id: opts.paymentId,
    p_engagement_id: opts.engagementId,
    p_purchaser_user_id: opts.purchaserUserId ?? null,
    p_stripe_payment_intent_id: opts.stripePaymentIntentId ?? null,
  })

  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Get a single Work Order by ID (service role).
 */
export async function getWorkOrder(
  workOrderId: string
): Promise<WorkOrder | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('id', workOrderId)
    .single()

  return data as WorkOrder | null
}

/**
 * Find a Work Order by Stripe checkout session ID.
 * Used for idempotency in webhook fulfillment.
 */
export async function findWorkOrderByCheckoutSession(
  stripeCheckoutSessionId: string
): Promise<WorkOrder | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('stripe_checkout_session_id', stripeCheckoutSessionId)
    .single()

  return data as WorkOrder | null
}

/**
 * List Work Orders for an organization (service role).
 */
export async function listWorkOrdersForOrg(
  organizationId: string
): Promise<WorkOrder[]> {
  const sc = createServiceClient()
  if (!sc) return []

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('organization_id', organizationId)
    .order('created_at', { ascending: false })

  return (data || []) as WorkOrder[]
}

/**
 * List Work Order updates (service role).
 * Returns only client-visible updates unless includeInternal is true.
 */
export async function listWorkOrderUpdates(
  workOrderId: string,
  includeInternal = false
): Promise<WorkOrderUpdate[]> {
  const sc = createServiceClient()
  if (!sc) return []

  let query = sc
    .from('ai_work_order_updates')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('created_at', { ascending: true })

  if (!includeInternal) {
    query = query.eq('is_client_visible', true)
  }

  const { data } = await query
  return (data || []) as WorkOrderUpdate[]
}

/**
 * Get the scope acceptance for a Work Order.
 */
export async function getScopeAcceptance(
  workOrderId: string
): Promise<WorkOrderScopeAcceptance | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_order_scope_acceptances')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  return data as WorkOrderScopeAcceptance | null
}

/**
 * Add a client input update to a Work Order.
 */
export async function addClientInput(opts: {
  workOrderId: string
  authorUserId: string
  body: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.authorUserId,
      author_role: 'client',
      update_type: 'client_input',
      body: opts.body,
      is_client_visible: true,
    })

  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Compute fulfillment state for checkout success polling.
 */
export async function getFulfillmentState(
  stripeCheckoutSessionId: string
): Promise<{ state: FulfillmentState; workOrder?: WorkOrder } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('stripe_checkout_session_id', stripeCheckoutSessionId)
    .single()

  if (!wo) return { error: 'Work Order not found for this checkout session' }

  const workOrder = wo as WorkOrder

  // Determine fulfillment state from Work Order status
  if (workOrder.status === 'payment_pending') {
    return { state: 'payment_pending', workOrder }
  }
  if (workOrder.status === 'paid' || workOrder.status === 'scoped' || workOrder.status === 'in_progress') {
    return { state: 'ready', workOrder }
  }
  if (workOrder.status === 'cancelled' || workOrder.status === 'refunded') {
    return { state: 'failed_support_required', workOrder }
  }
  if (workOrder.status === 'draft' || workOrder.status === 'awaiting_scope' || workOrder.status === 'awaiting_client_acceptance' || workOrder.status === 'awaiting_approval' || workOrder.status === 'awaiting_owner_approval' || workOrder.status === 'ready_for_checkout') {
    // Payment hasn't been recorded yet — webhook may not have processed
    return { state: 'fulfillment_pending', workOrder }
  }

  return { state: 'ready', workOrder }
}

/**
 * Transition Work Order status (service role, for advisor/admin operations).
 *
 * Section E/F: delegates to the `transition_work_order_status` RPC which
 * enforces the canonical transition matrix atomically (status update +
 * audit row in one transaction). Invalid transitions raise and are
 * surfaced as `{ success: false, error }`.
 */
export async function transitionWorkOrderStatus(
  workOrderId: string,
  newStatus: WorkOrderStatus,
  actorRole: 'advisor' | 'platform_admin' | 'client',
  actorUserId?: string,
  note?: string
): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc.rpc('transition_work_order_status', {
    p_work_order_id: workOrderId,
    p_new_status: newStatus,
    p_actor_role: actorRole,
    p_actor_user_id: actorUserId ?? null,
    p_note: note ?? null,
  })

  if (error) return { success: false, error: error.message }
  return { success: true }
}

// ============================================
// Advisor fulfillment operations
// ============================================

/**
 * Add an advisor update/note to a Work Order.
 * Advisor updates can be client-visible or internal (is_client_visible=false).
 * Uses service role to bypass the client-author trigger.
 */
export async function addAdvisorUpdate(opts: {
  workOrderId: string
  authorUserId: string
  body: string
  isClientVisible: boolean
  updateType?: UpdateType
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.authorUserId,
      author_role: 'advisor',
      update_type: opts.updateType || 'note',
      body: opts.body,
      is_client_visible: opts.isClientVisible,
    })

  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Compose/edit scope for a Work Order (advisor-side).
 *
 * Section B: sending a scope to the client must NEVER write
 * scope_status = 'accepted', scope_accepted_at, or scope_accepted_by. Those
 * are written ONLY by `acceptWorkOrderScope` when an authenticated customer
 * accepts the exact immutable version.
 *
 * When `sendToClient` is true, this creates an immutable scope version in
 * the `sent_to_client` state and transitions the Work Order to
 * `awaiting_client_acceptance`. When false, it saves a `proposed` version
 * (draft) without transitioning.
 */
export async function composeWorkOrderScope(opts: {
  workOrderId: string
  advisorUserId: string
  scopeTitle?: string
  scopeIncluded?: string
  scopeExcluded?: string
  requiredInputs?: string
  deliverableDescription?: string
  desiredOutcome?: string
  workType?: WorkType
  targetTiming?: string
  priceCents?: number
  sendToClient?: boolean
}): Promise<{ success: boolean; error?: string; workOrder?: WorkOrder; scopeVersionId?: string }> {
  // Load the current Work Order to build the snapshot from existing + new fields
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('id', opts.workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }

  const workOrder = wo as WorkOrder

  const snapshot: ScopeSnapshot = {
    work_type: opts.workType ?? workOrder.work_type,
    title: opts.scopeTitle ?? workOrder.scope_title ?? workOrder.title,
    desired_outcome: opts.desiredOutcome ?? workOrder.desired_outcome ?? '',
    scope_included: opts.scopeIncluded ?? workOrder.scope_included ?? '',
    scope_excluded: opts.scopeExcluded ?? workOrder.scope_excluded ?? '',
    required_inputs: opts.requiredInputs ?? workOrder.required_inputs ?? '',
    deliverable_description: opts.deliverableDescription ?? workOrder.deliverable_description ?? '',
    target_timing: opts.targetTiming ?? workOrder.scope_target_timing ?? null,
    price_cents: opts.priceCents ?? workOrder.scope_price_cents ?? workOrder.standard_price_cents ?? 50000,
    currency: workOrder.currency || 'USD',
    assumptions: [
      'Standard Work Order covers one bounded outcome.',
      'If the work is larger than one standard Work Order, additional Work Orders or a custom scope will be discussed before proceeding.',
      'The answer is allowed to be no — a recommendation to wait, buy, or simplify is a valid outcome.',
    ],
  }

  const versionResult = await createWorkOrderScopeVersion({
    workOrderId: opts.workOrderId,
    scopeSnapshot: snapshot,
    composedBy: opts.advisorUserId,
    sendToClient: opts.sendToClient,
  })

  if ('error' in versionResult) {
    return { success: false, error: versionResult.error }
  }

  // Reload the Work Order to return the updated row
  const { data: updatedWo } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('id', opts.workOrderId)
    .single()

  // Add scope change update record
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.advisorUserId,
      author_role: 'advisor',
      update_type: 'scope_change',
      body: opts.sendToClient
        ? `Scope v${versionResult.versionNumber} prepared and sent to client for acceptance.`
        : `Scope v${versionResult.versionNumber} draft saved.`,
      is_client_visible: opts.sendToClient,
    })

  return {
    success: true,
    workOrder: (updatedWo || undefined) as WorkOrder | undefined,
    scopeVersionId: versionResult.scopeVersionId,
  }
}

/**
 * Request client input on a Work Order.
 * Transitions to needs_client_input and creates an update record.
 */
export async function requestClientInput(opts: {
  workOrderId: string
  advisorUserId: string
  requestTitle: string
  whatIsNeeded: string
  whyItMatters?: string
  dueDate?: string | null
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  // Get current status
  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('status')
    .eq('id', opts.workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }

  // Transition to needs_client_input via validated RPC (atomic status + audit)
  const { error: rpcError } = await sc.rpc('transition_work_order_status', {
    p_work_order_id: opts.workOrderId,
    p_new_status: 'needs_client_input',
    p_actor_role: 'advisor',
    p_actor_user_id: opts.advisorUserId,
    p_note: opts.requestTitle,
  })

  if (rpcError) return { success: false, error: rpcError.message }

  // Build the request body
  const bodyParts = [opts.requestTitle, '', opts.whatIsNeeded]
  if (opts.whyItMatters) bodyParts.push('', `Why it matters: ${opts.whyItMatters}`)
  if (opts.dueDate) bodyParts.push('', `Needed by: ${opts.dueDate}`)

  // Add the client_input_requested detail record (separate from the
  // status_change audit row the RPC inserted; this carries the request body)
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.advisorUserId,
      author_role: 'advisor',
      update_type: 'client_input_requested',
      body: bodyParts.join('\n'),
      is_client_visible: true,
    })

  // Store request metadata
  await sc
    .from('ai_work_orders')
    .update({
      metadata: { input_request: { title: opts.requestTitle, needed: opts.whatIsNeeded, why: opts.whyItMatters, due: opts.dueDate } },
    })
    .eq('id', opts.workOrderId)

  return { success: true }
}

/**
 * Publish a deliverable for a Work Order.
 * Creates a deliverable record and optionally transitions to delivered.
 */
export async function publishDeliverable(opts: {
  workOrderId: string
  advisorUserId: string
  title: string
  description?: string
  artifactType: ArtifactType
  artifactUrl?: string
  artifactMetadata?: Record<string, unknown>
  isClientVisible?: boolean
  markDelivered?: boolean
}): Promise<{ deliverableId: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_order_deliverables')
    .insert({
      work_order_id: opts.workOrderId,
      title: opts.title,
      description: opts.description || null,
      artifact_type: opts.artifactType,
      artifact_url: opts.artifactUrl || null,
      artifact_metadata: opts.artifactMetadata || {},
      is_client_visible: opts.isClientVisible !== false,
      published_by: opts.advisorUserId,
      published_at: new Date().toISOString(),
    })
    .select('id')
    .single()

  if (error || !data) return { error: error?.message || 'Failed to publish deliverable' }

  // Add deliverable_published update record
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.advisorUserId,
      author_role: 'advisor',
      update_type: 'deliverable_published',
      body: `Deliverable published: ${opts.title}`,
      is_client_visible: opts.isClientVisible !== false,
    })

  // Optionally transition to delivered via validated RPC (atomic)
  if (opts.markDelivered) {
    const { error: rpcError } = await sc.rpc('transition_work_order_status', {
      p_work_order_id: opts.workOrderId,
      p_new_status: 'delivered',
      p_actor_role: 'advisor',
      p_actor_user_id: opts.advisorUserId,
      p_note: 'Work Order marked as delivered.',
    })
    if (rpcError) {
      // Non-fatal: deliverable was published; log the transition failure
      console.error('[publishDeliverable] transition to delivered failed:', rpcError.message)
    }
  }

  return { deliverableId: data.id }
}

/**
 * List deliverables for a Work Order.
 * Returns only client-visible deliverables unless includeInternal is true.
 */
export async function listDeliverables(
  workOrderId: string,
  includeInternal = false
): Promise<WorkOrderDeliverable[]> {
  const sc = createServiceClient()
  if (!sc) return []

  let query = sc
    .from('ai_work_order_deliverables')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('created_at', { ascending: false })

  if (!includeInternal) {
    query = query.eq('is_client_visible', true)
  }

  const { data } = await query
  return (data || []) as WorkOrderDeliverable[]
}

/**
 * Split a Work Order into multiple child Work Orders.
 * Each child has its own scope, acceptance, payment, and status.
 */
export async function splitWorkOrder(opts: {
  parentWorkOrderId: string
  advisorUserId: string
  splits: Array<{
    title: string
    workType?: WorkType
    desiredOutcome?: string
    scopeIncluded?: string
    priceCents?: number
  }>
}): Promise<{ childWorkOrderIds: string[] } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  // Get parent Work Order
  const { data: parent } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('id', opts.parentWorkOrderId)
    .single()

  if (!parent) return { error: 'Parent Work Order not found' }

  const childIds: string[] = []

  for (const split of opts.splits) {
    const { data: child, error } = await sc
      .from('ai_work_orders')
      .insert({
        organization_id: parent.organization_id,
        requested_by_user_id: parent.requested_by_user_id,
        source_offer_key: parent.source_offer_key,
        parent_work_order_id: opts.parentWorkOrderId,
        source_request_id: parent.source_request_id,
        source_request_type: parent.source_request_type,
        title: split.title,
        work_type: split.workType || parent.work_type,
        desired_outcome: split.desiredOutcome || null,
        scope_included: split.scopeIncluded || null,
        scope_status: 'needs_review',
        status: 'awaiting_scope',
        standard_price_cents: split.priceCents || 50000,
        currency: 'USD',
        metadata: { split_from: opts.parentWorkOrderId },
      })
      .select('id')
      .single()

    if (error || !child) {
      return { error: error?.message || 'Failed to create split Work Order' }
    }

    childIds.push(child.id)
  }

  // Add split update record on parent
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.parentWorkOrderId,
      author_user_id: opts.advisorUserId,
      author_role: 'advisor',
      update_type: 'split',
      body: `Work Order split into ${opts.splits.length} separate Work Orders.`,
      is_client_visible: true,
    })

  return { childWorkOrderIds: childIds }
}

/**
 * Create a Work Order draft from an Advisor Question (escalation flow).
 * Pre-populates from the question without charging.
 */
export async function createWorkOrderFromQuestion(opts: {
  organizationId: string
  requestedByUserId: string
  questionId: string
  questionSubject: string
  questionBody: string
  questionContext?: Record<string, unknown>
  suggestedWorkType?: WorkType
  suggestedOutcome?: string
}): Promise<{ workOrderId: string; workOrderNumber: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_orders')
    .insert({
      organization_id: opts.organizationId,
      requested_by_user_id: opts.requestedByUserId,
      source_offer_key: 'ai_automation_blueprint',
      source_request_id: opts.questionId,
      source_request_type: 'advisor_question',
      title: opts.questionSubject,
      work_type: opts.suggestedWorkType || 'other',
      desired_outcome: opts.suggestedOutcome || null,
      scope_included: null,
      scope_status: 'custom_scope_required',
      status: 'awaiting_scope',
      standard_price_cents: 50000,
      currency: 'USD',
      metadata: {
        source_question: opts.questionId,
        question_subject: opts.questionSubject,
        question_body: opts.questionBody,
        question_context: opts.questionContext || {},
      },
    })
    .select('id, work_order_number')
    .single()

  if (error || !data) return { error: error?.message || 'Failed to create Work Order from question' }

  // Add update record
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: data.id,
      author_role: 'advisor',
      update_type: 'note',
      body: `Work Order created from Advisor Question: "${opts.questionSubject}". The original question and context are attached.`,
      is_client_visible: true,
    })

  return { workOrderId: data.id, workOrderNumber: data.work_order_number }
}

/**
 * Request owner/admin approval for a Work Order created by a non-purchasing member.
 * Transitions to awaiting_owner_approval and notifies organization admins.
 */
export async function requestOwnerApproval(opts: {
  workOrderId: string
  requesterUserId: string
  requesterName?: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('status')
    .eq('id', opts.workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }

  const previousStatus = wo.status

  const { error } = await sc
    .from('ai_work_orders')
    .update({ status: 'awaiting_owner_approval' })
    .eq('id', opts.workOrderId)

  if (error) return { success: false, error: error.message }

  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.requesterUserId,
      author_role: 'client',
      update_type: 'owner_approval_requested',
      body: opts.requesterName
        ? `${opts.requesterName} requested this Work Order. Organization owner/admin approval required.`
        : 'Organization owner/admin approval required for this Work Order.',
      previous_status: previousStatus,
      new_status: 'awaiting_owner_approval',
      is_client_visible: true,
    })

  return { success: true }
}

/**
 * Owner/admin approves a Work Order and transitions to ready_for_checkout.
 * The owner must then complete checkout to pay.
 */
export async function approveWorkOrderByOwner(opts: {
  workOrderId: string
  ownerUserId: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('status, scope_status')
    .eq('id', opts.workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }
  if (wo.status !== 'awaiting_owner_approval') {
    return { success: false, error: 'Work Order is not awaiting owner approval' }
  }

  // If scope is already accepted, go to ready_for_checkout
  // If scope needs composition, go to awaiting_scope (advisor composes first)
  const newStatus: WorkOrderStatus = wo.scope_status === 'accepted' ? 'ready_for_checkout' : 'awaiting_scope'

  // Use the validated RPC for the transition + audit row (atomic).
  const { error: rpcError } = await sc.rpc('transition_work_order_status', {
    p_work_order_id: opts.workOrderId,
    p_new_status: newStatus,
    p_actor_role: 'client',
    p_actor_user_id: opts.ownerUserId,
    p_note: 'Organization owner/admin approved this Work Order.',
  })

  if (rpcError) return { success: false, error: rpcError.message }

  return { success: true }
}

/**
 * Owner/admin declines a Work Order request from a member.
 */
export async function declineWorkOrderByOwner(opts: {
  workOrderId: string
  ownerUserId: string
  reason?: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('status')
    .eq('id', opts.workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }
  if (wo.status !== 'awaiting_owner_approval') {
    return { success: false, error: 'Work Order is not awaiting owner approval' }
  }

  const { error: rpcError } = await sc.rpc('transition_work_order_status', {
    p_work_order_id: opts.workOrderId,
    p_new_status: 'cancelled',
    p_actor_role: 'client',
    p_actor_user_id: opts.ownerUserId,
    p_note: opts.reason ? `Work Order declined by organization owner/admin: ${opts.reason}` : 'Work Order declined by organization owner/admin.',
  })

  if (rpcError) return { success: false, error: rpcError.message }

  return { success: true }
}
