/**
 * Canonical AI Work Order domain logic.
 *
 * Work Orders are repeatable bounded transactions, NOT permanent entitlements.
 * One organization may have many Work Orders. Each has its own scope acceptance.
 *
 * Lifecycle:
 *   draft → awaiting_scope → awaiting_approval → ready_for_checkout
 *         → payment_pending → paid → scoped → in_progress
 *         → needs_client_input → in_review → delivered → completed
 *         (or cancelled / refunded at any point)
 *
 * Scope status (separate from work status):
 *   draft → needs_review → standard → accepted
 *   (or custom_scope_required for expanded scope)
 */

import { createServiceClient } from '@/lib/supabase'
import { createHash } from 'crypto'

// Re-export types from the types-only file (safe for client components)
export type {
  WorkOrderStatus,
  WorkOrderScopeStatus,
  WorkType,
  FulfillmentState,
  WorkOrder,
  WorkOrderScopeAcceptance,
  WorkOrderUpdate,
  ScopeSnapshot,
} from '@/lib/commercial/work-order-types'
export { statusLabel } from '@/lib/commercial/work-order-types'

// Import types for internal use
import type {
  WorkOrderStatus,
  WorkType,
  FulfillmentState,
  WorkOrder,
  WorkOrderScopeAcceptance,
  WorkOrderUpdate,
  ScopeSnapshot,
} from '@/lib/commercial/work-order-types'

// ============================================
// Scope rendering
// ============================================

/**
 * Build a canonical scope snapshot for a standard $500 Work Order.
 * The server generates this — the client does not supply the hash.
 */
export function buildStandardScopeSnapshot(params: {
  title: string
  workType: WorkType
  desiredOutcome: string
  scopeIncluded?: string
  scopeExcluded?: string
  requiredInputs?: string
  deliverableDescription?: string
  targetDate?: string | null
}): ScopeSnapshot {
  return {
    work_type: params.workType,
    title: params.title,
    desired_outcome: params.desiredOutcome,
    scope_included: params.scopeIncluded || 'One bounded piece of work as described in the intake and agreed in this scope.',
    scope_excluded: params.scopeExcluded || 'Work beyond the defined scope, additional integrations, or multi-system architecture. These may require additional Work Orders or a custom engagement.',
    required_inputs: params.requiredInputs || 'Access to relevant systems, data, or documentation as needed to complete the defined outcome.',
    deliverable_description: params.deliverableDescription || 'A focused deliverable matching the agreed scope: analysis, design, recommendation, configuration, or bounded implementation.',
    target_timing: params.targetDate || null,
    price_cents: 50000,
    currency: 'USD',
    assumptions: [
      'Standard Work Order covers one bounded outcome.',
      'If the work is larger than one standard Work Order, additional Work Orders or a custom scope will be discussed before proceeding.',
      'The answer is allowed to be no — a recommendation to wait, buy, or simplify is a valid outcome.',
    ],
  }
}

/**
 * Hash the scope snapshot for immutable acceptance record.
 */
export function hashScopeSnapshot(snapshot: ScopeSnapshot): string {
  const canonical = JSON.stringify({
    work_type: snapshot.work_type,
    title: snapshot.title,
    desired_outcome: snapshot.desired_outcome,
    scope_included: snapshot.scope_included,
    scope_excluded: snapshot.scope_excluded,
    required_inputs: snapshot.required_inputs,
    deliverable_description: snapshot.deliverable_description,
    target_timing: snapshot.target_timing,
    price_cents: snapshot.price_cents,
    currency: snapshot.currency,
    assumptions: snapshot.assumptions,
  })
  return createHash('sha256').update(canonical).digest('hex')
}

// ============================================
// Status language mapping (customer-facing)
// ============================================

// ============================================
// Database operations (service role)
// ============================================

/**
 * Create a Work Order draft. work_order_number is auto-generated by trigger.
 */
export async function createWorkOrderDraft(opts: {
  organizationId: string
  requestedByUserId?: string
  title: string
  workType?: WorkType
  desiredOutcome?: string
  scopeIncluded?: string
  scopeExcluded?: string
  requiredInputs?: string
  deliverableDescription?: string
  legacyQualificationId?: string
  standardPriceCents?: number
  targetDate?: string | null
  metadata?: Record<string, unknown>
}): Promise<{ workOrderId: string; workOrderNumber: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_orders')
    .insert({
      organization_id: opts.organizationId,
      requested_by_user_id: opts.requestedByUserId || null,
      source_offer_key: 'ai_automation_blueprint',
      legacy_qualification_id: opts.legacyQualificationId || null,
      title: opts.title,
      work_type: opts.workType || 'other',
      desired_outcome: opts.desiredOutcome || null,
      scope_included: opts.scopeIncluded || null,
      scope_excluded: opts.scopeExcluded || null,
      required_inputs: opts.requiredInputs || null,
      deliverable_description: opts.deliverableDescription || null,
      scope_status: 'draft',
      status: 'draft',
      standard_price_cents: opts.standardPriceCents ?? 50000,
      currency: 'USD',
      target_date: opts.targetDate || null,
      metadata: opts.metadata || {},
    })
    .select('id, work_order_number')
    .single()

  if (error || !data) {
    return { error: error?.message || 'Failed to create Work Order' }
  }

  return { workOrderId: data.id, workOrderNumber: data.work_order_number }
}

/**
 * Create a Work Order draft for custom/expanded scope.
 * Placed in advisor review queue, NOT checkout.
 */
export async function createCustomScopeWorkOrder(opts: {
  organizationId: string
  requestedByUserId?: string
  title: string
  workType?: WorkType
  desiredOutcome?: string
  legacyQualificationId?: string
  metadata?: Record<string, unknown>
}): Promise<{ workOrderId: string; workOrderNumber: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data, error } = await sc
    .from('ai_work_orders')
    .insert({
      organization_id: opts.organizationId,
      requested_by_user_id: opts.requestedByUserId || null,
      source_offer_key: 'ai_automation_blueprint',
      legacy_qualification_id: opts.legacyQualificationId || null,
      title: opts.title,
      work_type: opts.workType || 'other',
      desired_outcome: opts.desiredOutcome || null,
      scope_status: 'custom_scope_required',
      status: 'awaiting_scope',
      standard_price_cents: 50000,
      currency: 'USD',
      metadata: { ...opts.metadata || {}, custom_scope: true },
    })
    .select('id, work_order_number')
    .single()

  if (error || !data) {
    return { error: error?.message || 'Failed to create Work Order' }
  }

  return { workOrderId: data.id, workOrderNumber: data.work_order_number }
}

/**
 * Record scope acceptance for a Work Order.
 * Uses service role so accepted_by can be set to the authenticated user.
 */
export async function recordScopeAcceptance(opts: {
  workOrderId: string
  scopeSnapshot: ScopeSnapshot
  acceptedBy: string
}): Promise<{ acceptanceId: string } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const snapshot = opts.scopeSnapshot
  const hash = hashScopeSnapshot(snapshot)

  const { data, error } = await sc
    .from('ai_work_order_scope_acceptances')
    .insert({
      work_order_id: opts.workOrderId,
      scope_version: 1,
      rendered_scope_text: JSON.stringify(snapshot, null, 2),
      rendered_scope_json: snapshot as unknown as Record<string, unknown>,
      document_hash: hash,
      accepted_by: opts.acceptedBy,
      price_cents: snapshot.price_cents,
      currency: snapshot.currency,
    })
    .select('id')
    .single()

  if (error || !data) {
    return { error: error?.message || 'Failed to record scope acceptance' }
  }

  // Transition Work Order to ready_for_checkout
  await sc
    .from('ai_work_orders')
    .update({
      scope_status: 'accepted',
      status: 'ready_for_checkout',
      scope_accepted_at: new Date().toISOString(),
      scope_accepted_by: opts.acceptedBy,
      scope_included: snapshot.scope_included,
      scope_excluded: snapshot.scope_excluded,
      required_inputs: snapshot.required_inputs,
      deliverable_description: snapshot.deliverable_description,
    })
    .eq('id', opts.workOrderId)

  return { acceptanceId: data.id }
}

/**
 * Link a Stripe checkout session to a Work Order.
 * Called when checkout is created (before payment).
 */
export async function linkCheckoutSession(
  workOrderId: string,
  stripeCheckoutSessionId: string
): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc
    .from('ai_work_orders')
    .update({
      stripe_checkout_session_id: stripeCheckoutSessionId,
      status: 'payment_pending',
    })
    .eq('id', workOrderId)

  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Fulfill a Work Order after Stripe payment succeeds.
 * This is the webhook fulfillment path — uses service role.
 * Creates engagement, links payment, transitions status.
 */
export async function fulfillWorkOrder(opts: {
  workOrderId: string
  organizationId: string
  paymentId: string
  stripePaymentIntentId?: string
  engagementId: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  // Link payment + engagement to Work Order
  const { error: updateError } = await sc
    .from('ai_work_orders')
    .update({
      payment_id: opts.paymentId,
      engagement_id: opts.engagementId,
      stripe_payment_intent_id: opts.stripePaymentIntentId || null,
      status: 'paid',
      purchased_by_user_id: null, // set by caller if known
    })
    .eq('id', opts.workOrderId)

  if (updateError) return { success: false, error: updateError.message }

  // Add Work Order update record
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_role: 'platform_admin',
      update_type: 'payment_event',
      body: 'Payment received. Work Order is now active.',
      previous_status: 'payment_pending',
      new_status: 'paid',
      is_client_visible: true,
    })

  return { success: true }
}

/**
 * Get a single Work Order by ID (service role).
 */
export async function getWorkOrder(
  workOrderId: string
): Promise<WorkOrder | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('id', workOrderId)
    .single()

  return data as WorkOrder | null
}

/**
 * Find a Work Order by Stripe checkout session ID.
 * Used for idempotency in webhook fulfillment.
 */
export async function findWorkOrderByCheckoutSession(
  stripeCheckoutSessionId: string
): Promise<WorkOrder | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('stripe_checkout_session_id', stripeCheckoutSessionId)
    .single()

  return data as WorkOrder | null
}

/**
 * List Work Orders for an organization (service role).
 */
export async function listWorkOrdersForOrg(
  organizationId: string
): Promise<WorkOrder[]> {
  const sc = createServiceClient()
  if (!sc) return []

  const { data } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('organization_id', organizationId)
    .order('created_at', { ascending: false })

  return (data || []) as WorkOrder[]
}

/**
 * List Work Order updates (service role).
 * Returns only client-visible updates unless includeInternal is true.
 */
export async function listWorkOrderUpdates(
  workOrderId: string,
  includeInternal = false
): Promise<WorkOrderUpdate[]> {
  const sc = createServiceClient()
  if (!sc) return []

  let query = sc
    .from('ai_work_order_updates')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('created_at', { ascending: true })

  if (!includeInternal) {
    query = query.eq('is_client_visible', true)
  }

  const { data } = await query
  return (data || []) as WorkOrderUpdate[]
}

/**
 * Get the scope acceptance for a Work Order.
 */
export async function getScopeAcceptance(
  workOrderId: string
): Promise<WorkOrderScopeAcceptance | null> {
  const sc = createServiceClient()
  if (!sc) return null

  const { data } = await sc
    .from('ai_work_order_scope_acceptances')
    .select('*')
    .eq('work_order_id', workOrderId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  return data as WorkOrderScopeAcceptance | null
}

/**
 * Add a client input update to a Work Order.
 */
export async function addClientInput(opts: {
  workOrderId: string
  authorUserId: string
  body: string
}): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  const { error } = await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: opts.workOrderId,
      author_user_id: opts.authorUserId,
      author_role: 'client',
      update_type: 'client_input',
      body: opts.body,
      is_client_visible: true,
    })

  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Compute fulfillment state for checkout success polling.
 */
export async function getFulfillmentState(
  stripeCheckoutSessionId: string
): Promise<{ state: FulfillmentState; workOrder?: WorkOrder } | { error: string }> {
  const sc = createServiceClient()
  if (!sc) return { error: 'Service client unavailable' }

  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('*')
    .eq('stripe_checkout_session_id', stripeCheckoutSessionId)
    .single()

  if (!wo) return { error: 'Work Order not found for this checkout session' }

  const workOrder = wo as WorkOrder

  // Determine fulfillment state from Work Order status
  if (workOrder.status === 'payment_pending') {
    return { state: 'payment_pending', workOrder }
  }
  if (workOrder.status === 'paid' || workOrder.status === 'scoped' || workOrder.status === 'in_progress') {
    return { state: 'ready', workOrder }
  }
  if (workOrder.status === 'cancelled' || workOrder.status === 'refunded') {
    return { state: 'failed_support_required', workOrder }
  }
  if (workOrder.status === 'draft' || workOrder.status === 'awaiting_scope' || workOrder.status === 'awaiting_approval' || workOrder.status === 'ready_for_checkout') {
    // Payment hasn't been recorded yet — webhook may not have processed
    return { state: 'fulfillment_pending', workOrder }
  }

  return { state: 'ready', workOrder }
}

/**
 * Transition Work Order status (service role, for advisor/admin operations).
 */
export async function transitionWorkOrderStatus(
  workOrderId: string,
  newStatus: WorkOrderStatus,
  actorRole: 'advisor' | 'platform_admin',
  actorUserId?: string,
  note?: string
): Promise<{ success: boolean; error?: string }> {
  const sc = createServiceClient()
  if (!sc) return { success: false, error: 'Service client unavailable' }

  // Get current status for update record
  const { data: wo } = await sc
    .from('ai_work_orders')
    .select('status')
    .eq('id', workOrderId)
    .single()

  if (!wo) return { success: false, error: 'Work Order not found' }

  const previousStatus = wo.status

  // Update Work Order
  const updateFields: Record<string, unknown> = { status: newStatus }
  if (newStatus === 'delivered') updateFields.delivered_at = new Date().toISOString()
  if (newStatus === 'completed') updateFields.completed_at = new Date().toISOString()

  const { error: updateError } = await sc
    .from('ai_work_orders')
    .update(updateFields)
    .eq('id', workOrderId)

  if (updateError) return { success: false, error: updateError.message }

  // Add update record
  await sc
    .from('ai_work_order_updates')
    .insert({
      work_order_id: workOrderId,
      author_user_id: actorUserId || null,
      author_role: actorRole,
      update_type: 'status_change',
      body: note || `Status changed from ${previousStatus} to ${newStatus}`,
      previous_status: previousStatus,
      new_status: newStatus,
      is_client_visible: true,
    })

  return { success: true }
}
